# Generated by Django 3.2.22 on 2023-10-30 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TotalBlog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=60, null=True)),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(default='', max_length=20)),
                ('date', models.DateField()),
                ('time', models.CharField(choices=[('16:00', '16:00'), ('16:30', '16:30'), ('17:00', '17:00'), ('17:30', '17:30'), ('18:00', '18:00'), ('18:30', '18:30'), ('19:00', '19:00'), ('19:30', '19:30'), ('20:00', '20:00'), ('20:30', '20:30'), ('21:00', '21:00')], max_length=50)),
                ('occasion', models.CharField(choices=[('D&D', 'D&D'), ('Pathfinder', 'Pathfinder'), ('Thirsty Sword Lesbians', 'Thirsty Sword Lesbians'), ('Help me choose something!?', 'Help me choose something!?'), ('None', 'None')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
